//
// Created by leno on 4/18/23.
//

#ifndef LENOENGINE_VAOVBO_H
#define LENOENGINE_VAOVBO_H
#include <cstring>
#include "GL/glew.h"
#include "GLFW/glfw3.h"

/**
 * Holds information about one VBO
 * id is the id generated by Opengl
 * attrName is predefined, there should be MACROS or some constants
 */
struct VBO{
    const unsigned int id;
    const int attributeType;
};


/**
 * /**
 * It generates an ID for buffer and if copy value is set to true, will then copy the data into the
 * GPU ram.
 * This only initialize one buffer
 * @param vbo
 * @param copy
 * @param attributeType
 */
void initializeStaticDrawVbo(VBO* vbo,const void* data,int attributeType);

#endif //LENOENGINE_VAOVBO_H
